# ---------------------------------------------------------------------------
# merge_and_publish_bike_layers.py
# Created on: Mon May 24 2010 03:48:54 PM
#   (generated by David Knudsen)
# ---------------------------------------------------------------------------

# Import system modules
import sys, string, os, arcpy
from datetime import datetime

# Create the Geoprocessor object
gp = arcpy

installDir = gp.GetInstallInfo("desktop").get("InstallDir")

# Load required toolboxes...
gp.AddToolbox(os.path.join(installDir, "ArcToolbox/Toolboxes/Conversion Tools.tbx"))
gp.AddToolbox(os.path.join(installDir, "ArcToolbox/Toolboxes/Data Management Tools.tbx"))
gp.AddToolbox(os.path.join(installDir, "ArcToolbox/Toolboxes/Analysis Tools.tbx"))
gp.AddToolbox(os.path.join(installDir, "ArcToolbox/Toolboxes/Linear Referencing Tools.tbx"))
gp.env.overwriteOutput = 1
# gp.overwriteoutput = 1
gp.env.qualifiedFieldNames = "UNQUALIFIED"

# Parameters...
Xfer_GDB = gp.GetParameterAsText(0)
if (os.path.splitext(Xfer_GDB)[1] != u'.mdb'):
    gp.AddError("This tool will only operate on a personal (MS Access) geodatabase.")
else:
    Source_GDB = gp.GetParameterAsText(1)
    if (Source_GDB == "#" or Source_GDB == ""):
        if os.path.exists(r"S:\HQ\Planning\DataResources\GISDevelopment\Bikes\Workspace\CTPS\BikeDomains.mdb"):
            Source_GDB = r"S:\HQ\Planning\DataResources\GISDevelopment\Bikes\Workspace\CTPS\BikeDomains.mdb"
        else:
            Source_GDB = Xfer_GDB
        
    Metadata_file = gp.GetParameterAsText(2)
    if (Metadata_file == "#" or Metadata_file == ""):
        Metadata_file = r"S:\HQ\Planning\DataResources\GISDevelopment\Bikes\Workspace\CTPS\bicycle_accommodation_inventory_metadata.xml"
    
    # Local variables...
    ProgressStep = 0
    NumProgressSteps = 11

    Roads = "RoadSegments"
    BIKES = "BIKES"
    PHYSICAL = "PHYSICAL"
    PropAndProg = "ProgrammedAndProposed_bikes"
    Greenways = "Greenway_unpaved_bikes"
    CombinedEvents = "CombinedEvents"
    CombinedEventsSorted = "CombinedEventsSorted"
    FirstObjectIDLookup = "FirstObjectIDLookup"
    BikeInventory = "BikeInventory"

    Xfer_folder = os.path.dirname(Xfer_GDB)
    Xfer_GDB_name = os.path.basename(Xfer_GDB)

    BikeFacilityStatus = os.path.join(Xfer_GDB, "BikeFacilityStatus")
    BikeFacilityType = os.path.join(Xfer_GDB, "BikeFacilityType")
    SurfaceType = os.path.join(Xfer_GDB, "SurfaceType")
    BayStateGreenway = os.path.join(Xfer_GDB, "BayStateGreenway")
    YN = os.path.join(Xfer_GDB, "YN")

    Xfer_Roads = os.path.join(Xfer_GDB, "RoadSegments")
    Xfer_Roads_Layer = "RoadSegments_Layer"
    Xfer_BIKES = os.path.join(Xfer_GDB, "BIKES")
    Xfer_PHYSICAL = os.path.join(Xfer_GDB, "PHYSICAL")
    Xfer_PropAndProg = os.path.join(Xfer_GDB, PropAndProg)
    Xfer_Greenways = os.path.join(Xfer_GDB, Greenways)
    Xfer_CombinedEvents = os.path.join(Xfer_GDB, CombinedEvents)
    Xfer_CombinedEventsSorted = os.path.join(Xfer_GDB, CombinedEventsSorted)
    Xfer_FirstObjectIDLookup = os.path.join(Xfer_GDB, FirstObjectIDLookup)
    Xfer_BikeInventory = os.path.join(Xfer_GDB, BikeInventory)

    BikeSegsQuery = "BikeSegsQuery"
    CombinedEventsQuery = "CombinedEventsQuery"
    BikeEvents = "BikeEvents"
    CombinedEvents_View = "CombinedEvents_View"
    BikeInventory_Layer = "BikeInventory_Layer"

    BikeInventoryTemp = os.path.join(Xfer_GDB, "BikeInventoryTemp")

    gp.SetProgressor("step", "Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps), 0, NumProgressSteps, 1)

    # Process: Overlay BIKES and PHYSICAL events...
    gp.AddMessage("Merging bike and physical events...")
    event_props = "RoadSegment_ID LINE FromMeasure ToMeasure"
    gp.OverlayRouteEvents_lr(Xfer_BIKES, event_props, \
                             Xfer_PHYSICAL, event_props, \
                             "UNION", \
                             Xfer_CombinedEvents, \
                             event_props, \
                             "NO_ZERO", \
                             "FIELDS", \
                             "INDEX")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Make query table of combined events to sort on RoadSegment_ID and measures
    #          and also to exclude combined events that have no bike event component...
    gp.AddMessage("Sorting combined events...")
    gp.MakeQueryTable_management(Xfer_CombinedEvents, \
                                 CombinedEventsQuery, \
                                 "ADD_VIRTUAL_KEY_FIELD", \
                                 "", \
                                 "", \
                                 "[BikeFacilityStatus] IS NOT NULL AND [BikeFacilityStatus] > 0 AND [BikeFacilityType] <> 8 AND [FromMeasure] <> [ToMeasure] " + \
                                 "ORDER BY RoadSegment_ID, FromMeasure, ToMeasure")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Save query table to temporary event table...
    gp.AddMessage("...and saving them to temporary event table...")
    gp.CopyRows_management(CombinedEventsQuery, Xfer_CombinedEventsSorted)
    gp.AddIndex_management(Xfer_CombinedEventsSorted, "RoadSegment_ID", "SEG_TMP_ID_idx", "NON_UNIQUE", "NON_ASCENDING")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Create lookup table of first OBJECTID for every ROADSEGMENT_ID and assign ordinal to each event on the IDs...
    gp.AddMessage("Adding a field to contain a new 'BikeInventory_ID'...")
    gp.AddField_management(Xfer_CombinedEventsSorted, "BikeInventory_ID", "LONG", "", "", "", "BikeInventory_ID", "", "", "")
    gp.MakeTableView_management(Xfer_CombinedEventsSorted, CombinedEvents_View, "", "", "")
    gp.AddMessage("...and calculating it initially to be equal to the OBJECTID...")
    gp.CalculateField_management(CombinedEvents_View, "BikeInventory_ID", "[OBJECTID]", "VB", "")
    gp.AddMessage("...and creating a look up table of first OBJECTID for each RoadSegment_ID...")
    gp.Statistics_analysis(CombinedEvents_View, Xfer_FirstObjectIDLookup, "BikeInventory_ID FIRST", "RoadSegment_ID")
    gp.AddIndex_management(Xfer_FirstObjectIDLookup, "RoadSegment_ID", "Stats_Seg_idx", "UNIQUE", "ASCENDING")
    gp.AddMessage("...and joining to that look up table and calculating the new BikeInventory_ID...")
    gp.AddJoin_management(CombinedEvents_View, "RoadSegment_ID", Xfer_FirstObjectIDLookup, "RoadSegment_ID", "")
    gp.CalculateField_management(CombinedEvents_View, \
                                 "BikeInventory_ID", \
                                 "[" + CombinedEventsSorted + ".RoadSegment_ID] * 100 + [" + \
                                 CombinedEventsSorted + ".OBJECTID] - [" + FirstObjectIDLookup + ".FIRST_BikeInventory_ID]", \
                                 "VB", "")
    gp.RemoveJoin_management(CombinedEvents_View, FirstObjectIDLookup)
    gp.AddMessage("Adding additional fields for programmed and proposed bike features...")
    gp.AddField_management(Xfer_CombinedEventsSorted, "ProjectNum", "TEXT", "", "", "50", "ProjectNum", "", "", "")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Create and save event features...
    gp.AddMessage("Converting events into features and saving...")
    gp.MakeRouteEventLayer_lr(Xfer_Roads, "ROADSEGMENT_ID", Xfer_CombinedEventsSorted, "RoadSegment_ID LINE FromMeasure ToMeasure", BikeEvents, \
                              "", "NO_ERROR_FIELD", "NO_ANGLE_FIELD", "NORMAL", "ANGLE", "LEFT", "POINT")
    gp.CopyFeatures_management(BikeEvents, BikeInventoryTemp)

    # Process: Add fields not found in BIKES table but needed in published feature class and then copy to new feature class
    #          deleting and reordering fields in the process
    gp.AddMessage("...and adding other fields needed for final feature class...")
##    gp.AddField_management(BikeInventoryTemp,"FundingSource","TEXT","#","#","50","#","NULLABLE","NON_REQUIRED","#")    
##    gp.AddField_management(BikeInventoryTemp,"VisionName","TEXT","#","#","255","#","NULLABLE","NON_REQUIRED","#")    
    gp.AddField_management(BikeInventoryTemp,"DateLastProjectActivity","DATE","#","#","#","#","NULLABLE","NON_REQUIRED","#")

    gp.AddMessage("...and deleting and reordering fields...")
    gp.FeatureClassToFeatureClass_conversion(BikeInventoryTemp, \
                                             Xfer_GDB, \
                                             BikeInventory, \
                                             "[BikeFacilityType] <> 8 AND [BikeFacilityStatus] <> 0 AND [BikeFacilityStatus] IS NOT NULL AND [Shape_length] > 0", \
                                             "BikeInventory_ID 'BikeInventory ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",BikeInventory_ID,-1,-1;" + \
                                             "RoadSegment_ID 'RoadSegment ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",RoadSegment_ID,-1,-1;" + \
                                             "FromMeasure 'From Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",FromMeasure,-1,-1;" + \
                                             "ToMeasure 'To Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",ToMeasure,-1,-1;" + \
                                             "LocalName 'Local Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",LocalName,-1,-1;" + \
                                             "AlternateTrailName 'Alternate Trail Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",AlternateTrailName,-1,-1;" + \
                                             "RegionalName 'Regional Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",RegionalName,-1,-1;" + \
                                             "BayStateGreenway 'Bay State Greenway' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BayStateGreenway,-1,-1;" + \
                                             "BSGProposed 'BSG Proposed' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGProposed,-1,-1;" + \
                                             "BSGPreferred 'BSG Preferred' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGUltimate,-1,-1;" + \
                                             "BikeFacilityStatus 'Bike Facility Status' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityStatus,-1,-1;" + \
                                             "BikeFacilityType 'Bike Facility Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityType,-1,-1;" + \
                                             "BikeSurfaceWidthRight 'Bike Surface Width Right' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthRight,-1,-1;" + \
                                             "BikeSurfaceWidthLeft 'Bike Surface Width Left' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthLeft,-1,-1;" + \
                                             "SurfaceType 'Surface Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",SurfaceType,-1,-1;" + \
                                             "CurrentOwner 'Current Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",CurrentOwner,-1,-1;" + \
                                             "PreviousOwner 'Previous Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",PreviousOwner,-1,-1;" + \
                                             "Steward 'Steward' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",Steward,-1,-1;" + \
                                             "OpeningDate 'Opening Date' true true false 8 Date 0 0 ,First,#," + BikeInventoryTemp + ",OpeningDate,-1,-1;" + \
                                             "DateLastProjectActivity 'Date Last Project Activity' true true false 8 Date 0 0 ,First,#," + BikeInventoryTemp + ",,-1,-1;" + \
                                             "ProjectNum 'Project Number' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",ProjectNum,-1,-1;" + \
                                             "DataSource 'Data Source' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",DataSource,-1,-1;" + \
                                             "Websites 'Websites' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",Websites,-1,-1;" + \
                                             "BikeVolumeWeekdays 'Bike Volume Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekdays,-1,-1;" + \
                                             "BikeVolumeWeekends 'Bike Volume Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekends,-1,-1;" + \
                                             "BikeVolumeYearWeekdays 'Bike Volume Year Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekdays,-1,-1;" + \
                                             "BikeVolumeYearWeekends 'Bike Volume Year Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekends,-1,-1;" + \
                                             "PlanMapID 'Plan Map ID' true true false 10 Text 0 0 ,First,#," + BikeInventoryTemp + ",PlanMapID,-1,-1", \
                                             "")

##                                             "VisionName 'Vision Name' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",VisionName,-1,-1;" + \
##                                             "FundingSource 'Funding Source' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",FundingSource,-1,-1;" + \

    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Create copy of proposed and programmed bike features and prep for appending...
    gp.AddMessage("Copying proposed and programmed bike features to temporary feature class...")
    gp.Copy_management(Xfer_PropAndProg, BikeInventoryTemp)
    gp.AddMessage("...and adding a 'BikeInventory_ID' field...")
    gp.AddField_management(BikeInventoryTemp, "BikeInventory_ID", "LONG", "", "", "", "BikeInventory_ID", "", "", "")
    gp.MakeFeatureLayer_management(BikeInventoryTemp, BikeInventory_Layer, \
                                   "([Retired_Record] = 0 OR [Retired_Record] IS NULL) AND [BikeFacilityStatus] IS NOT NULL AND ([BikeFacilityType] <> 8 OR [BikeFacilityType] IS NULL)")
    gp.AddMessage("...and calculating it...")
    gp.CalculateField_management(BikeInventory_Layer, "BikeInventory_ID", "[OBJECTID] + 100000000", "VB", "")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Append prepped proposed and programmed bike features to existing bike features...
    gp.AddMessage("Appending prepared proposed and programmed bike features to existing bike features...")
    gp.Append_management(BikeInventory_Layer, \
                         Xfer_BikeInventory, \
                         "NO_TEST", \
                         "RoadSegment_ID 'RoadSegment ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",RoadSegment_ID,-1,-1;" + \
                         "FromMeasure 'From Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",FromMeasure,-1,-1;" + \
                         "ToMeasure 'To Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",ToMeasure,-1,-1;" + \
                         "RegionalName 'Regional Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",RegionalName,-1,-1;" + \
                         "LocalName 'Local Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",LocalName,-1,-1;" + \
                         "AlternateTrailName 'Alternate Trail Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",AlternateTrailName,-1,-1;" + \
                         "BikeFacilityStatus 'Bike Facility Status' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityStatus,-1,-1;" + \
                         "BikeFacilityType 'Bike Facility Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityType,-1,-1;" + \
                         "BikeSurfaceWidthRight 'Bike Surface Width Right' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthRight,-1,-1;" + \
                         "BikeSurfaceWidthLeft 'Bike Surface Width Left' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthLeft,-1,-1;" + \
                         "BikeVolumeWeekdays 'Bike Volume Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekdays,-1,-1;" + \
                         "BikeVolumeWeekends 'Bike Volume Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekends,-1,-1;" + \
                         "BikeVolumeYearWeekdays 'Bike Volume Year Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekdays,-1,-1;" + \
                         "BikeVolumeYearWeekends 'Bike Volume Year Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekends,-1,-1;" + \
                         "ProjectNum 'Project Number' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",ProjectNum,-1,-1;" + \
                         "DataSource 'Data Source' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",DataSource,-1,-1;" + \
                         "Websites 'Websites' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",Websites,-1,-1;" + \
                         "PlanMapID 'Plan Map ID' true true false 10 Text 0 0 ,First,#," + BikeInventoryTemp + ",PlanMapID,-1,-1;" + \
                         "CurrentOwner 'Current Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",CurrentOwner,-1,-1;" + \
                         "PreviousOwner 'Previous Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",PreviousOwner,-1,-1;" + \
                         "Steward 'Steward' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",Steward,-1,-1;" + \
                         "OpeningDate 'Opening Date' true true false 8 Date 0 0 ,First,#," + BikeInventoryTemp + ",OpeningDate,-1,-1;" + \
                         "BayStateGreenway 'Bay State Greenway' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BayStateGreenway,-1,-1;" + \
                         "BSGProposed 'BSG Proposed' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGProposed,-1,-1;" + \
                         "BSGPreferred 'BSG Preferred' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGUltimate,-1,-1;" + \
                         "DateLastProjectActivity 'Date Last Project Activity' true true false 8 Date 0 0 ,First,#," + BikeInventoryTemp + ",DateLastProjectActivity,-1,-1;" + \
                         "SurfaceType 'Surface Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",SurfaceType,-1,-1;" + \
                         "BikeInventory_ID 'BikeInventory ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",BikeInventory_ID,-1,-1;" + \
                         "Shape_Length 'Shape_Length' false true true 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",Shape_Length,-1,-1", \
                         "")
##                         "VisionName 'Vision Name' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",VisionName,-1,-1;" + \
##                         "FundingSource 'Funding Source' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",FundingSource,-1,-1;" + \

    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Create copy of greenway (minimally improved) bike features and prep for appending...
    gp.AddMessage("Copying greenway (minimally improved) bike features to temporary feature class...")
    gp.Copy_management(Xfer_Greenways, BikeInventoryTemp)
    gp.AddMessage("...and adding a 'BikeInventory_ID' field...")
    gp.AddField_management(BikeInventoryTemp, "BikeInventory_ID", "LONG", "", "", "", "BikeInventory_ID", "", "", "")
    gp.MakeFeatureLayer_management(BikeInventoryTemp, BikeInventory_Layer, "([Retired_Record] = 0 OR [Retired_Record] IS NULL) AND [BikeFacilityStatus] IS NOT NULL AND ([BikeFacilityType] <> 8 OR [BikeFacilityType] IS NULL)")
    gp.AddMessage("...and calculating it...")
    gp.CalculateField_management(BikeInventory_Layer, "BikeInventory_ID", "[OBJECTID] + 200000000", "VB", "")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Append prepped greenway bike features to existing bike features...
    gp.AddMessage("Appending prepared greenway (minimally improved) bike features to existing bike features...")
    gp.Append_management(BikeInventory_Layer, \
                         Xfer_BikeInventory, \
                         "NO_TEST", \
                         "RoadSegment_ID 'RoadSegment ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",RoadSegment_ID,-1,-1;" + \
                         "FromMeasure 'From Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",FromMeasure,-1,-1;" + \
                         "ToMeasure 'To Measure' true true false 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",ToMeasure,-1,-1;" + \
                         "RegionalName 'Regional Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",RegionalName,-1,-1;" + \
                         "LocalName 'Local Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",LocalName,-1,-1;" + \
                         "AlternateTrailName 'Alternate Trail Name' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",AlternateTrailName,-1,-1;" + \
                         "BikeFacilityStatus 'Bike Facility Status' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityStatus,-1,-1;" + \
                         "BikeFacilityType 'Bike Facility Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeFacilityType,-1,-1;" + \
                         "BikeSurfaceWidthRight 'Bike Surface Width Right' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthRight,-1,-1;" + \
                         "BikeSurfaceWidthLeft 'Bike Surface Width Left' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeSurfaceWidthLeft,-1,-1;" + \
                         "BikeVolumeWeekdays 'Bike Volume Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekdays,-1,-1;" + \
                         "BikeVolumeWeekends 'Bike Volume Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeWeekends,-1,-1;" + \
                         "BikeVolumeYearWeekdays 'Bike Volume Year Weekdays' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekdays,-1,-1;" + \
                         "BikeVolumeYearWeekends 'Bike Volume Year Weekends' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",BikeVolumeYearWeekends,-1,-1;" + \
                         "ProjectNum 'Project Number' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",ProjectNum,-1,-1;" + \
                         "DataSource 'Data Source' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",DataSource,-1,-1;" + \
                         "Websites 'Websites' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",Websites,-1,-1;" + \
                         "PlanMapID 'Plan Map ID' true true false 10 Text 0 0 ,First,#," + BikeInventoryTemp + ",PlanMapID,-1,-1;" + \
                         "CurrentOwner 'Current Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",CurrentOwner,-1,-1;" + \
                         "PreviousOwner 'Previous Owner' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",PreviousOwner,-1,-1;" + \
                         "Steward 'Steward' true true false 100 Text 0 0 ,First,#," + BikeInventoryTemp + ",Steward,-1,-1;" + \
                         "OpeningDate 'Opening Date' true true false 8 Date 0 0 ,First,#," + BikeInventoryTemp + ",OpeningDate,-1,-1;" + \
                         "BayStateGreenway 'Bay State Greenway' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BayStateGreenway,-1,-1;" + \
                         "BSGProposed 'BSG Proposed' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGProposed,-1,-1;" + \
                         "BSGPreferred 'BSG Preferred' true true false 1 Text 0 0 ,First,#," + BikeInventoryTemp + ",BSGUltimate,-1,-1;" + \
                         "SurfaceType 'Surface Type' true true false 2 Short 0 0 ,First,#," + BikeInventoryTemp + ",SurfaceType,-1,-1;" + \
                         "BikeInventory_ID 'BikeInventory ID' true true false 4 Long 0 0 ,First,#," + BikeInventoryTemp + ",BikeInventory_ID,-1,-1;" + \
                         "Shape_Length 'Shape_Length' false true true 8 Double 0 0 ,First,#," + BikeInventoryTemp + ",Shape_Length,-1,-1", \
                         "")
##                         "VisionName 'Vision Name' true true false 50 Text 0 0 ,First,#," + BikeInventoryTemp + ",VisionName,-1,-1;" + \
##                         "FundingSource 'Funding Source' true true false 255 Text 0 0 ,First,#," + BikeInventoryTemp + ",FundingSource,-1,-1;" + \

    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Transfer domains...
    if (Source_GDB != Xfer_GDB):
        gp.AddMessage("Getting domains from source database...")
        gp.DomainToTable_management(Source_GDB, "dmnBikeFacilityStatus", BikeFacilityStatus, "CODE", "DESCRIPTION", "")
        gp.DomainToTable_management(Source_GDB, "dmnBikeFacilityType", BikeFacilityType, "CODE", "DESCRIPTION", "")
        gp.DomainToTable_management(Source_GDB, "dmnSurfaceType", SurfaceType, "CODE", "DESCRIPTION", "")
        gp.DomainToTable_management(Source_GDB, "BayStateGreenway", BayStateGreenway, "CODE", "DESCRIPTION", "")
        gp.DomainToTable_management(Source_GDB, "dmnYN", YN, "CODE", "DESCRIPTION", "")

        gp.AddMessage("...and putting them in transfer database...")
        gp.TableToDomain_management(BikeFacilityStatus, "CODE", "DESCRIPTION", Xfer_GDB, "dmnBikeFacilityStatus", "Codes for status of bicycle facilities", "REPLACE")
        gp.TableToDomain_management(BikeFacilityType, "CODE", "DESCRIPTION", Xfer_GDB, "dmnBikeFacilityType", "Codes for type of bicycle facility", "REPLACE")
        gp.TableToDomain_management(SurfaceType, "CODE", "DESCRIPTION", Xfer_GDB, "dmnSurfaceType", "Codes for pavement surface type", "REPLACE")
        gp.TableToDomain_management(BayStateGreenway, "CODE", "DESCRIPTION", Xfer_GDB, "dmnBayStateGreenway", "Codes for Bay State Greenway corridors", "REPLACE")
        gp.TableToDomain_management(YN, "CODE", "DESCRIPTION", Xfer_GDB, "dmnYN", "Codes for Yes/No", "REPLACE")

    gp.AddMessage("Assigning domains to appropriate fields in BikeInventory...")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "BikeFacilityStatus", "dmnBikeFacilityStatus", "")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "BikeFacilityType", "dmnBikeFacilityType", "")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "SurfaceType", "dmnSurfaceType", "")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "BayStateGreenway", "dmnBayStateGreenway", "")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "BSGProposed", "dmnYN", "")
    gp.AssignDomainToField_management(Xfer_BikeInventory, "BSGPreferred", "dmnYN", "")
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)

    # Process: Assign template metadata to bicycle accommodation inventory, if the indicated xml file can be found
    if (os.path.exists(Metadata_file)):
        gp.AddMessage("Attaching template metadata to feature class...")
        # gp.MetadataImporter_conversion(Metadata_file,Xfer_BikeInventory)
        gp.ImportMetadata_conversion(Metadata_file,"FROM_FGDC",Xfer_BikeInventory,"DISABLED")

    # Process: Clean up and compact transfer database...
    gp.AddMessage("Adding index to BikeInventory_ID...")
    gp.AddIndex_management(Xfer_BikeInventory, "BikeInventory_ID", "BikeInvID_idx", "UNIQUE", "NON_ASCENDING")
    gp.AddMessage("Removing temporary objects in the database...")
    gp.Delete_management(Xfer_CombinedEvents, "Table")
    gp.Delete_management(Xfer_CombinedEventsSorted, "Table")
    gp.Delete_management(Xfer_FirstObjectIDLookup, "Table")
    gp.Delete_management(BikeInventoryTemp, "Feature class")
    gp.AddMessage("Compacting transfer database...")
    gp.Compact_management(Xfer_GDB)
    ProgressStep = ProgressStep + 1
    gp.SetProgressorLabel("Step " + str(ProgressStep + 1) + " of " + str(NumProgressSteps))
    gp.SetProgressorPosition(ProgressStep)
